version: '3.8'

services:
  config:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://microservice:microservice@db_config/config
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    volumes:
      - .:/backendservice
    depends_on:
      db_config:
        condition: service_healthy
    networks:
      - shared_network

  config_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python consumer.py
    environment:
      - DATABASE_URL=mysql://microservice:microservice@db_config/config
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672/
    depends_on:
      - config
    volumes:
      - .:/app
    networks:
      - shared_network

  db_config:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: config
      MYSQL_USER: microservice
      MYSQL_PASSWORD: microservice
      MYSQL_ROOT_PASSWORD: microservice
    volumes:
      - db_data_config:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_network

volumes:
  db_data_config:

networks:
  shared_network:
    external: true
